<?php 
    define ('API_KEY', "SUA_CHAVE_DE_API_TESTE");
    define ('ENC_KEY', "SUA_CHAVE_DE_CRIPTOGRAFIA_TESTE");

    define ('RECEBEDOR_01', "ID_PRIMEIRO_RECEBEDOR");
    define ('RECEBEDOR_02', "ID_SEGUNDO_RECEBEDOR");

?>